apiVersion: v1
kind: Service
metadata:
    name: hdfs-namenode-service
    labels:
        app: hdfs-namenode
spec:
    ports:
    - port: 50070
      name: web
    - port: 8020
      name: fs
    clusterIP: None
    selector:
        app: hdfs-namenode
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hdfs-namenode
  name: hdfs-namenode-service-extern
spec:
  type: NodePort
  ports:
  - port: 50070
  selector:
    app: hdfs-namenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: hdfs-namenode
    labels:
        app: hdfs-namenode
spec:
    serviceName: hdfs-namenode-service
    replicas: 1
    selector:
        matchLabels:
            app: hdfs-namenode
    template:
        metadata:
            labels:
                app: hdfs-namenode
        spec:
            containers:
            - name: hdfs-namenode
              image: fronepi/hdfs-namenode
              imagePullPolicy: Always
              env:
              - name: CLUSTER_NAME
                value: "test-cluster"
              - name: YARN_CONF_yarn_nodemanager_aux___services
                value: "mapreduce_shuffle"
              ports:
              - name: web
                containerPort: 50070
              - name: fs
                containerPort: 8020
