apiVersion: v1
kind: Service
metadata:
    name: historyserver-service
    labels:
        app: historyserver
spec:
    ports:
    - port: 19888
      name: web
    - port: 10020
      name: hs
    clusterIP: None
    selector:
        app: historyserver
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: historyserver
  name: historyserver-service-extern
spec:
  type: NodePort
  ports:
  - port: 19888
  selector:
    app: historyserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: historyserver
    labels:
        app: historyserver
spec:
    serviceName: historyserver-service
    replicas: 1
    selector:
        matchLabels:
            app: historyserver
    template:
        metadata:
            labels:
                app: historyserver
        spec:
            containers:
            - name: historyserver
              image: fronepi/historyserver
              imagePullPolicy: Always
              env:
              - name: CLUSTER_NAME
                value: "test-cluster"
              - name: YARN_CONF_yarn_nodemanager_aux___services
                value: "mapreduce_shuffle"
              ports:
              - name: web
                containerPort: 19888
              - name: hs
                containerPort: 10020
